### ISSUE TITLE
Unable to parse weekly ILRS SINEX files.

### ISSUE THREAD

**Issue by vangelis-z** [DSOlab/libsinex#5]
Example SINEX file: https://cddis.nasa.gov/archive/slr/products/pos+eop/2015/151217/ilrsa.pos+eop.151217.v135.snx.gz

Output of 
  test-sinex.out ilrsa.pos+eop.151217.v135.snx

[ERROR] Seems SINEX was not read till EOF! (traceback: mark_blocks)
ERROR. Failed to create SINEX instance from file ilrsa.pos+eop.151217.v135.snx
[ERROR] Failed to parse blocks in SINEX file

**Comment by xanthospap** [comment]
Think it is fixed.

The '%ENDSNX' mark in the SINEX file was followed by a newline and/or space. Fixed function dso::Sinex::mark_blocks() 
in sinex.cpp to exit correctly if:
`if (!std::strncmp(line, "%ENDSNX", 7))` and NOT `if (!std::strcmp(line, "%ENDSNX"))`

Rest of tests seem to pass

**Comment by xanthospap** [comment]
@vangelis-z close issue and merge if ok
